const cards = [
  {
    "country": "США",
    "director": "Стивен Кайак ",
    "duration": 61,
    "year": "2010",
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.",
    "image": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "trailerLink": "https://www.youtube.com/watch?v=UXcqcdYABFw",
    "thumbnail": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "movieId": 1,
    "nameRU": "«Роллинг Стоунз» в изгнании",
    "nameEN": "Stones in Exile",
    "like": []
  },
  {
    "country": "США",
    "director": "Стивен Кайак ",
    "duration": 61,
    "year": "2010",
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.",
    "image": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "trailerLink": "https://www.youtube.com/watch?v=UXcqcdYABFw",
    "thumbnail": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "movieId": 2,
    "nameRU": "«Роллинг Стоунз» в изгнании",
    "nameEN": "Stones in Exile",
    "like": []
  },
  {
    "country": "США",
    "director": "Стивен Кайак ",
    "duration": 61,
    "year": "2010",
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.",
    "image": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "trailerLink": "https://www.youtube.com/watch?v=UXcqcdYABFw",
    "thumbnail": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "movieId": 3,
    "nameRU": "«Роллинг Стоунз» в изгнании",
    "nameEN": "Stones in Exile",
    "like": []
  },
  {
    "country": "США",
    "director": "Стивен Кайак ",
    "duration": 61,
    "year": "2010",
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.",
    "image": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "trailerLink": "https://www.youtube.com/watch?v=UXcqcdYABFw",
    "thumbnail": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "movieId": 4,
    "nameRU": "«Роллинг Стоунз» в изгнании",
    "nameEN": "Stones in Exile",
    "like": []
  },
  {
    "country": "США",
    "director": "Стивен Кайак ",
    "duration": 61,
    "year": "2010",
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.",
    "image": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "trailerLink": "https://www.youtube.com/watch?v=UXcqcdYABFw",
    "thumbnail": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "movieId": 5,
    "nameRU": "«Роллинг Стоунз» в изгнании",
    "nameEN": "Stones in Exile",
    "like": []
  },
  {
    "country": "США",
    "director": "Стивен Кайак ",
    "duration": 61,
    "year": "2010",
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.",
    "image": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "trailerLink": "https://www.youtube.com/watch?v=UXcqcdYABFw",
    "thumbnail": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "movieId": 6,
    "nameRU": "«Роллинг Стоунз» в изгнании",
    "nameEN": "Stones in Exile",
    "like": []
  },
  {
    "country": "США",
    "director": "Стивен Кайак ",
    "duration": 61,
    "year": "2010",
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.",
    "image": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "trailerLink": "https://www.youtube.com/watch?v=UXcqcdYABFw",
    "thumbnail": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "movieId": 7,
    "nameRU": "«Роллинг Стоунз» в изгнании",
    "nameEN": "Stones in Exile",
    "like": []
  },
  {
    "country": "США",
    "director": "Стивен Кайак ",
    "duration": 61,
    "year": "2010",
    "description": "В конце 1960-х группа «Роллинг Стоунз», несмотря на все свои мегахиты и сверхуспешные концертные туры, была разорена. Виной всему — бездарный менеджмент и драконовское налогообложение в Британии. Тогда музыканты приняли не самое простое для себя решение: летом 1971 года после выхода альбома «Stiсky Fingers» они отправились на юг Франции записывать новую пластинку. Именно там, на Лазурном Берегу, в арендованном Китом Ричардсом подвале виллы Неллькот родился сборник «Exile on Main St.», который стал лучшим альбомом легендарной группы.",
    "image": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "trailerLink": "https://www.youtube.com/watch?v=UXcqcdYABFw",
    "thumbnail": "https://anime-star.ru/wp-content/uploads/2021/12/Nyashnye-anime-avatarki-tyan_04.jpg",
    "movieId": 8,
    "nameRU": "«Роллинг Стоунз» в изгнании",
    "nameEN": "Stones in Exile",
    "like": []
  },
];

export default cards;